version: '3.8'
services:
  react-app:
    build:
      context: ./player     # Updated to point to the player directory
      dockerfile: Dockerfile.player
    ports:
      - "3000:80"             # Map port 80 in the container to port 3000 on the host
    depends_on:
      - api

  api:
    build:
      context: ./server       # Updated to point to the server directory
      dockerfile: Dockerfile.server
    ports:
      - "8003:8003"           # Map port 8003 in the container to port 8003 on the host
    environment:
      - MONGO_URI=mongodb+srv://ngvuser:25538098@cluster0.9rsdwyc.mongodb.net/football_mern?retryWrites=true&w=majority&appName=Cluster0
